// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package reuse

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadReuseport returns the embedded CollectionSpec for reuseport.
func loadReuseport() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ReuseportBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load reuseport: %w", err)
	}

	return spec, err
}

// loadReuseportObjects loads reuseport and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*reuseportObjects
//	*reuseportPrograms
//	*reuseportMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadReuseportObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadReuseport()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// reuseportSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type reuseportSpecs struct {
	reuseportProgramSpecs
	reuseportMapSpecs
	reuseportVariableSpecs
}

// reuseportProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type reuseportProgramSpecs struct {
	SelectOrMigrate *ebpf.ProgramSpec `ebpf:"select_or_migrate"`
}

// reuseportMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type reuseportMapSpecs struct {
	Listeners *ebpf.MapSpec `ebpf:"listeners"`
}

// reuseportVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type reuseportVariableSpecs struct {
	ProbeAddr *ebpf.VariableSpec `ebpf:"probe_addr"`
}

// reuseportObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadReuseportObjects or ebpf.CollectionSpec.LoadAndAssign.
type reuseportObjects struct {
	reuseportPrograms
	reuseportMaps
	reuseportVariables
}

func (o *reuseportObjects) Close() error {
	return _ReuseportClose(
		&o.reuseportPrograms,
		&o.reuseportMaps,
	)
}

// reuseportMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadReuseportObjects or ebpf.CollectionSpec.LoadAndAssign.
type reuseportMaps struct {
	Listeners *ebpf.Map `ebpf:"listeners"`
}

func (m *reuseportMaps) Close() error {
	return _ReuseportClose(
		m.Listeners,
	)
}

// reuseportVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadReuseportObjects or ebpf.CollectionSpec.LoadAndAssign.
type reuseportVariables struct {
	ProbeAddr *ebpf.Variable `ebpf:"probe_addr"`
}

// reuseportPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadReuseportObjects or ebpf.CollectionSpec.LoadAndAssign.
type reuseportPrograms struct {
	SelectOrMigrate *ebpf.Program `ebpf:"select_or_migrate"`
}

func (p *reuseportPrograms) Close() error {
	return _ReuseportClose(
		p.SelectOrMigrate,
	)
}

func _ReuseportClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed reuseport_bpfel.o
var _ReuseportBytes []byte
