// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package reuse

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadSockopt returns the embedded CollectionSpec for sockopt.
func loadSockopt() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SockoptBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sockopt: %w", err)
	}

	return spec, err
}

// loadSockoptObjects loads sockopt and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sockoptObjects
//	*sockoptPrograms
//	*sockoptMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSockoptObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSockopt()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sockoptSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockoptSpecs struct {
	sockoptProgramSpecs
	sockoptMapSpecs
	sockoptVariableSpecs
}

// sockoptProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockoptProgramSpecs struct {
	Setsockopt *ebpf.ProgramSpec `ebpf:"setsockopt"`
	Sockcreate *ebpf.ProgramSpec `ebpf:"sockcreate"`
}

// sockoptMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockoptMapSpecs struct {
}

// sockoptVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockoptVariableSpecs struct {
}

// sockoptObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSockoptObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockoptObjects struct {
	sockoptPrograms
	sockoptMaps
	sockoptVariables
}

func (o *sockoptObjects) Close() error {
	return _SockoptClose(
		&o.sockoptPrograms,
		&o.sockoptMaps,
	)
}

// sockoptMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSockoptObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockoptMaps struct {
}

func (m *sockoptMaps) Close() error {
	return _SockoptClose()
}

// sockoptVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSockoptObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockoptVariables struct {
}

// sockoptPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSockoptObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockoptPrograms struct {
	Setsockopt *ebpf.Program `ebpf:"setsockopt"`
	Sockcreate *ebpf.Program `ebpf:"sockcreate"`
}

func (p *sockoptPrograms) Close() error {
	return _SockoptClose(
		p.Setsockopt,
		p.Sockcreate,
	)
}

func _SockoptClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sockopt_bpfel.o
var _SockoptBytes []byte
