// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package reuse

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type trackerIpKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	trackerMapIgnoredAddrs  = "ignored_addrs"
	trackerMapSocketTracker = "socket_tracker"
	trackerProgTrackIngress = "track_ingress"
)

// loadTracker returns the embedded CollectionSpec for tracker.
func loadTracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TrackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tracker: %w", err)
	}

	return spec, err
}

// loadTrackerObjects loads tracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*trackerObjects
//	*trackerPrograms
//	*trackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTrackerObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// trackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trackerSpecs struct {
	trackerProgramSpecs
	trackerMapSpecs
	trackerVariableSpecs
}

// trackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trackerProgramSpecs struct {
	TrackIngress *ebpf.ProgramSpec `ebpf:"track_ingress"`
}

// trackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trackerMapSpecs struct {
	IgnoredAddrs  *ebpf.MapSpec `ebpf:"ignored_addrs"`
	SocketTracker *ebpf.MapSpec `ebpf:"socket_tracker"`
}

// trackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trackerVariableSpecs struct {
}

// trackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type trackerObjects struct {
	trackerPrograms
	trackerMaps
	trackerVariables
}

func (o *trackerObjects) Close() error {
	return _TrackerClose(
		&o.trackerPrograms,
		&o.trackerMaps,
	)
}

// trackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type trackerMaps struct {
	IgnoredAddrs  *ebpf.Map `ebpf:"ignored_addrs"`
	SocketTracker *ebpf.Map `ebpf:"socket_tracker"`
}

func (m *trackerMaps) Close() error {
	return _TrackerClose(
		m.IgnoredAddrs,
		m.SocketTracker,
	)
}

// trackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type trackerVariables struct {
}

// trackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type trackerPrograms struct {
	TrackIngress *ebpf.Program `ebpf:"track_ingress"`
}

func (p *trackerPrograms) Close() error {
	return _TrackerClose(
		p.TrackIngress,
	)
}

func _TrackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracker_bpfel.o
var _TrackerBytes []byte
