kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  InPlacePodVerticalScaling: true
  UserNamespacesSupport: true
  InPlacePodVerticalScalingAllocatedStatus: true
nodes:
  - role: control-plane
    image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
  - role: worker
    image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
    extraMounts:
      - hostPath: /proc
        containerPath: /host/proc
    labels:
      zeropod.ctrox.dev/node: "true"
  - role: worker
    image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
    extraMounts:
      - hostPath: /proc
        containerPath: /host/proc
    labels:
      zeropod.ctrox.dev/node: "true"
