// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: shim.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerPhase int32

const (
	ContainerPhase_SCALED_DOWN       ContainerPhase = 0
	ContainerPhase_RUNNING           ContainerPhase = 1
	ContainerPhase_STOPPING          ContainerPhase = 2
	ContainerPhase_CHECKPOINT_FAILED ContainerPhase = 3
	ContainerPhase_RESTORE_FAILED    ContainerPhase = 4
)

// Enum value maps for ContainerPhase.
var (
	ContainerPhase_name = map[int32]string{
		0: "SCALED_DOWN",
		1: "RUNNING",
		2: "STOPPING",
		3: "CHECKPOINT_FAILED",
		4: "RESTORE_FAILED",
	}
	ContainerPhase_value = map[string]int32{
		"SCALED_DOWN":       0,
		"RUNNING":           1,
		"STOPPING":          2,
		"CHECKPOINT_FAILED": 3,
		"RESTORE_FAILED":    4,
	}
)

func (x ContainerPhase) Enum() *ContainerPhase {
	p := new(ContainerPhase)
	*p = x
	return p
}

func (x ContainerPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_shim_proto_enumTypes[0].Descriptor()
}

func (ContainerPhase) Type() protoreflect.EnumType {
	return &file_shim_proto_enumTypes[0]
}

func (x ContainerPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerPhase.Descriptor instead.
func (ContainerPhase) EnumDescriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{0}
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_shim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type SubscribeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeStatusRequest) Reset() {
	*x = SubscribeStatusRequest{}
	mi := &file_shim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeStatusRequest) ProtoMessage() {}

func (x *SubscribeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeStatusRequest.ProtoReflect.Descriptor instead.
func (*SubscribeStatusRequest) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeStatusRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*ContainerMetrics    `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_shim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsResponse) GetMetrics() []*ContainerMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerRequest) Reset() {
	*x = ContainerRequest{}
	mi := &file_shim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRequest) ProtoMessage() {}

func (x *ContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRequest.ProtoReflect.Descriptor instead.
func (*ContainerRequest) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ContainerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PodName       string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,4,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	Phase         ContainerPhase         `protobuf:"varint,5,opt,name=phase,proto3,enum=zeropod.shim.v1.ContainerPhase" json:"phase,omitempty"`
	EventTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	EventDuration *durationpb.Duration   `protobuf:"bytes,7,opt,name=event_duration,json=eventDuration,proto3" json:"event_duration,omitempty"`
	EventLog      string                 `protobuf:"bytes,8,opt,name=event_log,json=eventLog,proto3" json:"event_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStatus) Reset() {
	*x = ContainerStatus{}
	mi := &file_shim_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatus) ProtoMessage() {}

func (x *ContainerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatus.ProtoReflect.Descriptor instead.
func (*ContainerStatus) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerStatus) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ContainerStatus) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *ContainerStatus) GetPhase() ContainerPhase {
	if x != nil {
		return x.Phase
	}
	return ContainerPhase_SCALED_DOWN
}

func (x *ContainerStatus) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *ContainerStatus) GetEventDuration() *durationpb.Duration {
	if x != nil {
		return x.EventDuration
	}
	return nil
}

func (x *ContainerStatus) GetEventLog() string {
	if x != nil {
		return x.EventLog
	}
	return ""
}

type ContainerMetrics struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Name                   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PodName                string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace           string                 `protobuf:"bytes,3,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	LastCheckpoint         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lastCheckpoint,proto3" json:"lastCheckpoint,omitempty"`
	LastRestore            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=lastRestore,proto3" json:"lastRestore,omitempty"`
	LastCheckpointDuration *durationpb.Duration   `protobuf:"bytes,6,opt,name=lastCheckpointDuration,proto3" json:"lastCheckpointDuration,omitempty"`
	LastRestoreDuration    *durationpb.Duration   `protobuf:"bytes,7,opt,name=lastRestoreDuration,proto3" json:"lastRestoreDuration,omitempty"`
	Running                bool                   `protobuf:"varint,8,opt,name=running,proto3" json:"running,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ContainerMetrics) Reset() {
	*x = ContainerMetrics{}
	mi := &file_shim_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMetrics) ProtoMessage() {}

func (x *ContainerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_shim_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMetrics.ProtoReflect.Descriptor instead.
func (*ContainerMetrics) Descriptor() ([]byte, []int) {
	return file_shim_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerMetrics) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ContainerMetrics) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *ContainerMetrics) GetLastCheckpoint() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheckpoint
	}
	return nil
}

func (x *ContainerMetrics) GetLastRestore() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRestore
	}
	return nil
}

func (x *ContainerMetrics) GetLastCheckpointDuration() *durationpb.Duration {
	if x != nil {
		return x.LastCheckpointDuration
	}
	return nil
}

func (x *ContainerMetrics) GetLastRestoreDuration() *durationpb.Duration {
	if x != nil {
		return x.LastRestoreDuration
	}
	return nil
}

func (x *ContainerMetrics) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

var File_shim_proto protoreflect.FileDescriptor

const file_shim_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"shim.proto\x12\x0fzeropod.shim.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\">\n" +
	"\x0eMetricsRequest\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"F\n" +
	"\x16SubscribeStatusRequest\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"N\n" +
	"\x0fMetricsResponse\x12;\n" +
	"\ametrics\x18\x01 \x03(\v2!.zeropod.shim.v1.ContainerMetricsR\ametrics\"\"\n" +
	"\x10ContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc6\x02\n" +
	"\x0fContainerStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x04 \x01(\tR\fpodNamespace\x125\n" +
	"\x05phase\x18\x05 \x01(\x0e2\x1f.zeropod.shim.v1.ContainerPhaseR\x05phase\x129\n" +
	"\n" +
	"event_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\x12@\n" +
	"\x0eevent_duration\x18\a \x01(\v2\x19.google.protobuf.DurationR\reventDuration\x12\x1b\n" +
	"\tevent_log\x18\b \x01(\tR\beventLog\"\xa2\x03\n" +
	"\x10ContainerMetrics\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x03 \x01(\tR\fpodNamespace\x12B\n" +
	"\x0elastCheckpoint\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastCheckpoint\x12<\n" +
	"\vlastRestore\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastRestore\x12Q\n" +
	"\x16lastCheckpointDuration\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x16lastCheckpointDuration\x12K\n" +
	"\x13lastRestoreDuration\x18\a \x01(\v2\x19.google.protobuf.DurationR\x13lastRestoreDuration\x12\x18\n" +
	"\arunning\x18\b \x01(\bR\arunning*g\n" +
	"\x0eContainerPhase\x12\x0f\n" +
	"\vSCALED_DOWN\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\f\n" +
	"\bSTOPPING\x10\x02\x12\x15\n" +
	"\x11CHECKPOINT_FAILED\x10\x03\x12\x12\n" +
	"\x0eRESTORE_FAILED\x10\x042\x86\x02\n" +
	"\x04Shim\x12L\n" +
	"\aMetrics\x12\x1f.zeropod.shim.v1.MetricsRequest\x1a .zeropod.shim.v1.MetricsResponse\x12P\n" +
	"\tGetStatus\x12!.zeropod.shim.v1.ContainerRequest\x1a .zeropod.shim.v1.ContainerStatus\x12^\n" +
	"\x0fSubscribeStatus\x12'.zeropod.shim.v1.SubscribeStatusRequest\x1a .zeropod.shim.v1.ContainerStatus0\x01B*Z(github.com/ctrox/zeropod/api/shim/v1/;v1b\x06proto3"

var (
	file_shim_proto_rawDescOnce sync.Once
	file_shim_proto_rawDescData []byte
)

func file_shim_proto_rawDescGZIP() []byte {
	file_shim_proto_rawDescOnce.Do(func() {
		file_shim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shim_proto_rawDesc), len(file_shim_proto_rawDesc)))
	})
	return file_shim_proto_rawDescData
}

var file_shim_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shim_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shim_proto_goTypes = []any{
	(ContainerPhase)(0),            // 0: zeropod.shim.v1.ContainerPhase
	(*MetricsRequest)(nil),         // 1: zeropod.shim.v1.MetricsRequest
	(*SubscribeStatusRequest)(nil), // 2: zeropod.shim.v1.SubscribeStatusRequest
	(*MetricsResponse)(nil),        // 3: zeropod.shim.v1.MetricsResponse
	(*ContainerRequest)(nil),       // 4: zeropod.shim.v1.ContainerRequest
	(*ContainerStatus)(nil),        // 5: zeropod.shim.v1.ContainerStatus
	(*ContainerMetrics)(nil),       // 6: zeropod.shim.v1.ContainerMetrics
	(*emptypb.Empty)(nil),          // 7: google.protobuf.Empty
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 9: google.protobuf.Duration
}
var file_shim_proto_depIdxs = []int32{
	7,  // 0: zeropod.shim.v1.MetricsRequest.empty:type_name -> google.protobuf.Empty
	7,  // 1: zeropod.shim.v1.SubscribeStatusRequest.empty:type_name -> google.protobuf.Empty
	6,  // 2: zeropod.shim.v1.MetricsResponse.metrics:type_name -> zeropod.shim.v1.ContainerMetrics
	0,  // 3: zeropod.shim.v1.ContainerStatus.phase:type_name -> zeropod.shim.v1.ContainerPhase
	8,  // 4: zeropod.shim.v1.ContainerStatus.event_time:type_name -> google.protobuf.Timestamp
	9,  // 5: zeropod.shim.v1.ContainerStatus.event_duration:type_name -> google.protobuf.Duration
	8,  // 6: zeropod.shim.v1.ContainerMetrics.lastCheckpoint:type_name -> google.protobuf.Timestamp
	8,  // 7: zeropod.shim.v1.ContainerMetrics.lastRestore:type_name -> google.protobuf.Timestamp
	9,  // 8: zeropod.shim.v1.ContainerMetrics.lastCheckpointDuration:type_name -> google.protobuf.Duration
	9,  // 9: zeropod.shim.v1.ContainerMetrics.lastRestoreDuration:type_name -> google.protobuf.Duration
	1,  // 10: zeropod.shim.v1.Shim.Metrics:input_type -> zeropod.shim.v1.MetricsRequest
	4,  // 11: zeropod.shim.v1.Shim.GetStatus:input_type -> zeropod.shim.v1.ContainerRequest
	2,  // 12: zeropod.shim.v1.Shim.SubscribeStatus:input_type -> zeropod.shim.v1.SubscribeStatusRequest
	3,  // 13: zeropod.shim.v1.Shim.Metrics:output_type -> zeropod.shim.v1.MetricsResponse
	5,  // 14: zeropod.shim.v1.Shim.GetStatus:output_type -> zeropod.shim.v1.ContainerStatus
	5,  // 15: zeropod.shim.v1.Shim.SubscribeStatus:output_type -> zeropod.shim.v1.ContainerStatus
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_shim_proto_init() }
func file_shim_proto_init() {
	if File_shim_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shim_proto_rawDesc), len(file_shim_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shim_proto_goTypes,
		DependencyIndexes: file_shim_proto_depIdxs,
		EnumInfos:         file_shim_proto_enumTypes,
		MessageInfos:      file_shim_proto_msgTypes,
	}.Build()
	File_shim_proto = out.File
	file_shim_proto_goTypes = nil
	file_shim_proto_depIdxs = nil
}
