// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package socket

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfIpv6Addr struct {
	_       structs.HostLayout
	U6Addr8 [16]uint8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	KretprobeInetCskAccept *ebpf.ProgramSpec `ebpf:"kretprobe__inet_csk_accept"`
	TcpRcvStateProcess     *ebpf.ProgramSpec `ebpf:"tcp_rcv_state_process"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	PodKubeletAddrsV4 *ebpf.MapSpec `ebpf:"pod_kubelet_addrs_v4"`
	PodKubeletAddrsV6 *ebpf.MapSpec `ebpf:"pod_kubelet_addrs_v6"`
	TcpEvents         *ebpf.MapSpec `ebpf:"tcp_events"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	PodKubeletAddrsV4 *ebpf.Map `ebpf:"pod_kubelet_addrs_v4"`
	PodKubeletAddrsV6 *ebpf.Map `ebpf:"pod_kubelet_addrs_v6"`
	TcpEvents         *ebpf.Map `ebpf:"tcp_events"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.PodKubeletAddrsV4,
		m.PodKubeletAddrsV6,
		m.TcpEvents,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	KretprobeInetCskAccept *ebpf.Program `ebpf:"kretprobe__inet_csk_accept"`
	TcpRcvStateProcess     *ebpf.Program `ebpf:"tcp_rcv_state_process"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.KretprobeInetCskAccept,
		p.TcpRcvStateProcess,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
