apiVersion: apps/v1
kind: Deployment
metadata:
  name: freezer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freezer
  template:
    metadata:
      labels:
        app: freezer
      annotations:
        zeropod.ctrox.dev/scaledown-duration: 10s
        zeropod.ctrox.dev/migrate: "freezer"
    spec:
      runtimeClassName: zeropod
      containers:
        - image: ctrox/freezer:latest
          name: freezer
          args: ["-memory", "128"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
