apiVersion: v1
kind: Pod
metadata:
  name: http-echo
  labels:
    app: echo
  annotations:
    zeropod.ctrox.dev/ports-map: "container1=8080;container2=8082"
    zeropod.ctrox.dev/container-names: "container1"
    zeropod.ctrox.dev/scaledown-duration: 5s
spec:
  runtimeClassName: zeropod
  containers:
    - image: registry.k8s.io/e2e-test-images/agnhost:2.39
      name: container1
      args:
        - netexec
        - --http-port=8080
        - --udp-port=-1
      ports:
        - containerPort: 8080
      startupProbe:
        httpGet:
          port: 8080
          path: /
        periodSeconds: 1
    - image: ealen/echo-server
      name: container2
      args:
        - --port=8081
      ports:
        - containerPort: 8081
